### ISSUE TITLE
convert underscores in attribute names to hyphens

### ISSUE THREAD

**Issue by RossPaterson** [fitnr/svgis#11] opened 2022-05-22 10:35 UTC
This is currently only an issue with the `fill_rule` attribute, which generates `fill_rule="evenodd"`, instead of the expected `fill-rule="evenodd"`. But in general SVG uses hyphens in attribute names, which would presumably be reflected by underscores in Python variables.

**Comment by fitnr** [comment] 2022-05-22 14:16
The issue isn't in the `toattribs` function, which doesn't do any munging on attribute names besides removing ampersands. The incorrect `fill_rule` attribute was used in several places in the SVG generation code. I just pushed a fix to include in the next release.

**Closed** 2022-05-30 15:08 UTC
Labels: bug
